### ISSUE TITLE
Listing only last 5 video segments

### ISSUE THREAD

**Issue by Vish005** [OpenWatch/FFmpegWrapper#11]
I got 16 .ts files, but the m3u8 list is only showing the last 5.

**Comment by OnlyInAmerica** [comment]
That's how HLS "Live Session" operate by default, and is what FFmpeg produces. If you want to make another sort of manifest that, say, contains all segments, that's up to you. The [Kickflip iOS SDK](https://github.com/Kickflip/kickflip-ios-sdk) has a method for accomplishing this which you're free to use.

**Comment by Vish005** [comment]
At last I fixed this issue by setting the hls size in the FFOutputFile.m using the following code.

av_opt_set_int(formatContext->priv_data, "hls_list_size", list_size, 0);

In my opinion you can provide a property in your wrapper class to set the hls size list, so that your wrapper can be used more easily, without editing your classes.
