### ISSUE TITLE
Convert Video (.mov) to Audio (.m4a or mp3)

### ISSUE THREAD

**Issue by vinced45** [OpenWatch/FFmpegWrapper#6]
I'm at a lost at the values needed in the NSDictionary to convert a video file to audio. Any help is appreciated.

**Comment by chrisballinger** [comment]
Hey man, sorry, this project isn't really maintained anymore. You will probably need to modify the code a bit to accomplish that.

**Comment by vinced45** [comment]
Ok thanks for the response. I'll close this out and take a look at the code. Thanks
